// //Import Nextjs Components
// import { NextIntlClientProvider } from "next-intl";
// import { getMessages } from "next-intl/server";
// import { notFound } from "next/navigation";
// import type { Metadata } from "next";
// import localFont from "next/font/local";
// // Import CSS
// import "./globals.css";

// // Import Local Components
// import { ThemeProvider } from "./src/app/components/theme-provider";
// import { Navbar } from "./src/app/components/TopNavigation/Navbar";
// import { routing } from "@/i18n/routing";

// // Import Local Variables
// import { pages } from "./src/app/[locale]/coreVariables";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
//   params: { locale },
// }: {
//   children: React.ReactNode;
//   params: { locale: string };
// }) {
//   // Ensure that the incoming `locale` is valid
//   if (!routing.locales.includes(locale as any)) {
//     notFound();
//   }

//   // Providing all messages to the client
//   // side is the easiest way to get started
//   const messages = await getMessages();

//   return (
//     <html lang={locale}>
//       <body>
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <NextIntlClientProvider messages={messages}>
//             {/* Navbar */}
//             <Navbar pages={pages} />
//             {children}
//           </NextIntlClientProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
